task:
  timeout_in: 120m
  
  container:
    image: nixpkgs/nix-flakes:latest
    kvm: true
    cpu: 4
    memory: 8G

  # compute_engine_instance:
  #   image_project: ubuntu-os-cloud
  #   image_family: family/ubuntu-2204-lts
  #   platform: linux
  #   architecture: amd64
  #   cpu: 4
  #   memory: 16G
  #   nested_virtualization: true

  matrix:
    - name: Example Task
      only_if: $BRANCH == "main"
      nix_store_cache:
        folder: /nix/store
      test_script:
        - nix run .#test-e2e-example

